In [2]:
import torch

In [14]:
x = torch.arange(12)
print(x)

print(x.shape)

x = x.reshape(3, 4)
print(x)
print(x.shape)

x = torch.zeros(3, 4)
print(x)
x = torch.ones(3, 4)
print(x)



x = torch.tensor([[1.0, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(f"x: {x}")
print(f"y: {y}")

print(f"x + y: {x + y}")
print(f"x - y: {x - y}")
print(f"x * y: {x * y}")
print(f"x / y: {x / y}")

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
x: tensor([[1., 2., 3.],
        [4., 5., 6.]])
y: tensor([[ 7,  8,  9],
        [10, 11, 12]])
x + y: tensor([[ 8., 10., 12.],
        [14., 16., 18.]])
x - y: tensor([[-6., -6., -6.],
        [-6., -6., -6.]])
x * y: tensor([[ 7., 16., 27.],
        [40., 55., 72.]])
x / y: tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])


In [20]:
import torch as troch
x = troch.arange(12, dtype=torch.float32).reshape(3, 4)
y = troch.tensor([[6, 7, 8, 9], [10, 11, 12, 13], [1, 2, 3, 4]], dtype=torch.float32)
print(f"x: {x}")
print(f"y: {y}")

X = torch.cat((x, y), dim=0)# Concatenate along the first dimension\
print(f"X: {X}")
X = torch.cat((x, y), dim=1)# Concatenate along the second dimension
print(f"X: {X}")

x: tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
y: tensor([[ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [ 1.,  2.,  3.,  4.]])
X: tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [ 1.,  2.,  3.,  4.]])
X: tensor([[ 0.,  1.,  2.,  3.,  6.,  7.,  8.,  9.],
        [ 4.,  5.,  6.,  7., 10., 11., 12., 13.],
        [ 8.,  9., 10., 11.,  1.,  2.,  3.,  4.]])


In [26]:
X.sum()

before = id(X)
X = 1 + X
id(X) == before


Z = torch.zeros_like(X)
print(f"Z: {Z}")
print(f"Z id : {id(Z)}")

Z[:] = X + 1
print(f"Z id : {id(Z)}")

Z: tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
Z id : 5097463376
Z id : 5097463376


In [27]:
A = X.numpy()
B = torch.tensor(A)
print(f"A: {A}")
print(f"B: {B}")
print(type(A))
print(type(B))

A: [[ 5.  6.  7.  8. 11. 12. 13. 14.]
 [ 9. 10. 11. 12. 15. 16. 17. 18.]
 [13. 14. 15. 16.  6.  7.  8.  9.]]
B: tensor([[ 5.,  6.,  7.,  8., 11., 12., 13., 14.],
        [ 9., 10., 11., 12., 15., 16., 17., 18.],
        [13., 14., 15., 16.,  6.,  7.,  8.,  9.]])
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
