In [37]:
from torch.utils.tensorboard import SummaryWriter
    
from PIL import Image
import numpy as np 
writer = SummaryWriter('logs')

# writer.add_image()

image_path ='./practice_data/train/ants_image/0013035.jpg'
# image_path ='./practice_data/train/ants_image/5650366_e22b7e1065.jpg'
img = Image.open(image_path)

print(f'img : {img}')
print(f'img type : {type(img)}')

img_array = np.array(img)
print(f'img_array : {img_array}')
print(f'img_array type : {type(img_array)}')
print(f'img_array shape : {img_array.shape}')


writer.add_image('test', img_array, 2, dataformats='HWC') 

# writer.add_scalar()
# y = x 
for i in range(100):
    writer.add_scalar('y=x', i, i)

# y = 2x
for i in range(100):
    writer.add_scalar('y=2x', 2*i, i)

writer.close()

img : <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=768x512 at 0x306A726D0>
img type : <class 'PIL.JpegImagePlugin.JpegImageFile'>
img_array : [[[ 80 151 233]
  [ 80 151 233]
  [ 80 151 233]
  ...
  [ 81 152 234]
  [ 79 150 232]
  [ 76 147 229]]

 [[ 81 152 234]
  [ 81 152 234]
  [ 81 152 234]
  ...
  [ 81 152 234]
  [ 79 150 232]
  [ 76 147 229]]

 [[ 82 153 235]
  [ 82 153 235]
  [ 82 153 235]
  ...
  [ 80 151 233]
  [ 79 150 232]
  [ 77 148 230]]

 ...

 [[ 87 160 237]
  [ 87 160 237]
  [ 86 159 236]
  ...
  [ 44  92 141]
  [ 95 158 235]
  [ 90 157 228]]

 [[ 87 160 237]
  [ 87 160 237]
  [ 86 159 236]
  ...
  [ 84 147 226]
  [ 90 160 255]
  [ 84 152 233]]

 [[ 87 160 237]
  [ 87 160 237]
  [ 86 159 236]
  ...
  [ 79 160 242]
  [ 78 159 250]
  [ 84 161 233]]]
img_array type : <class 'numpy.ndarray'>
img_array shape : (512, 768, 3)
