In [ ]:
import torch

# type check
a = torch.randn(2,3)

print(f'a type: {a.type()}')

print(f'a type: {type(a)}')

print(f'a type: {isinstance(a, torch.Tensor)}')

print(f'a type: {isinstance(a, torch.cuda.DoubleTensor)}')


a = torch.tensor(1.)

print(f'a shape: {a.shape}')

b = torch.tensor([1.])
print(f'b shape: {b.shape}')

torch.FloatTensor(3)

a type: torch.FloatTensor
a type: <class 'torch.Tensor'>
a type: True
a type: False
a shape: torch.Size([])
b shape: torch.Size([1])


tensor([0., 0., 0.])

In [18]:
torch.cuda.is_available()

dir(torch)

dir(torch.cuda)

dir(torch.cuda.is_available())
help(torch.cuda.is_available)

Help on function is_available in module torch.cuda:

is_available() -> bool
    Return a bool indicating if CUDA is currently available.



In [7]:
import torch

# argmax 函数 可以返回张量中每个元素的最大值对应的索引
outputs = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
# 输出为每行最大值的索引
# 2, 2
print(outputs.argmax(1))
# 输出为每列最大值的索引
# 1,0,0
print(outputs.argmax(0))

preds = outputs.argmax(1)
targes = torch.tensor([2, 0])
print()
print((preds == targes).sum())

tensor([2, 2])
tensor([1, 0, 0])

tensor(1)
